# Generated by Django 6.1.1 on 2026-09-16 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО кандидата')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidates/photos/', verbose_name='Фотография')),
                ('photo_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Ссылка на фото')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Курс')),
                ('position', models.CharField(default='Президент студенческого совета', max_length=255, verbose_name='Должность')),
                ('short_bio', models.TextField(blank=True, verbose_name='Краткая биография')),
                ('program', models.TextField(blank=True, verbose_name='Предвыборная программа')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Выборы')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
