# Generated by Django 6.1.1 on 2026-09-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(blank=True, default='Кандидат', max_length=255, verbose_name='Должность'),
        ),
    ]
