# Generated by Django 5.2.7 on 2026-09-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_course_alter_candidate_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position_ky',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Кызмат орду (KY)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='program_ky',
            field=models.TextField(blank=True, default='', verbose_name='Шайлоо алдындагы программасы (KY)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='short_bio_ky',
            field=models.TextField(blank=True, default='', verbose_name='Кыскача өмүр баяны (KY)'),
        ),
    ]
