# Generated by Django 6.1.1 on 2026-09-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер-администратор'), ('university_admin', 'Администратор университета'), ('observer', 'Сотрудник (только просмотр)')], default='university_admin', max_length=30, verbose_name='Роль'),
        ),
    ]
