# Generated by Django 6.1.1 on 2026-09-16 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_ky', models.CharField(max_length=255, verbose_name='Аталышы (KY)')),
                ('code', models.SlugField(unique=True, verbose_name='Код университета (slug)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['name'],
            },
        ),
    ]
