# Generated by Django 6.1.1 on 2026-09-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_registration_open',
            field=models.BooleanField(default=True, verbose_name='Регистрация студентов открыта'),
        ),
    ]
