# Generated by Django 5.2.7 on 2026-09-19 07:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос (RU)')),
                ('question_ky', models.CharField(blank=True, default='', max_length=255, verbose_name='Вопрос (KY)')),
                ('answer', models.TextField(verbose_name='Ответ (RU)')),
                ('answer_ky', models.TextField(blank=True, default='', verbose_name='Ответ (KY)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ (FAQ)',
                'verbose_name_plural': 'Вопросы и ответы (FAQ)',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_ky', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (KY)')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Краткое описание (RU)')),
                ('summary_ky', models.TextField(blank=True, default='', verbose_name='Краткое описание (KY)')),
                ('content', models.TextField(verbose_name='Полное содержание (RU)')),
                ('content_ky', models.TextField(blank=True, default='', verbose_name='Полное содержание (KY)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='URL изображения')),
                ('category', models.CharField(choices=[('official', 'Официально'), ('elections', 'Выборы'), ('tech', 'Технологии'), ('students', 'Студенчество')], default='official', max_length=50, verbose_name='Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('author_name', models.CharField(default='Пресс-служба Dobush.kg', max_length=100, verbose_name='Имя автора')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
