# Generated by Django 5.2.7 on 2026-09-19 07:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Идентификатор (slug)')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_ky', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (KY)')),
                ('content', models.TextField(verbose_name='Полный текст (RU)')),
                ('content_ky', models.TextField(blank=True, default='', verbose_name='Полный текст (KY)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
                'ordering': ['slug'],
            },
        ),
    ]
