# Generated by Django 6.1.1 on 2026-09-16 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=100, verbose_name='Номер/код студента')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО студента')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('course', models.PositiveSmallIntegerField(default=1, verbose_name='Курс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=10, verbose_name='Код подтверждения')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает в')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Сессия аутентификации студента',
                'verbose_name_plural': 'Сессии аутентификации студентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Успешно импортировано')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Количество ошибок')),
                ('errors_detail', models.JSONField(blank=True, default=list, verbose_name='Детали ошибок')),
                ('status', models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='universities.university', verbose_name='Университет')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Пакет загрузки студентов',
                'verbose_name_plural': 'Пакеты загрузки студентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='uploaded_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.uploadbatch', verbose_name='Пакет загрузки'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('university', 'student_id')},
        ),
    ]
