# Generated by Django 6.1.1 on 2026-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Хэш пароля'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер/код студента'),
        ),
    ]
