# Generated by Django 6.1.1 on 2026-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_unique_together_student_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/', verbose_name='Фотография'),
        ),
    ]
