# Generated by Django 5.2.17 on 2026-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="auth_version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Увеличивается при деактивации, смене пароля и security reset. Токен с устаревшей версией немедленно перестаёт действовать. Стартует с 1, чтобы отличать «версия есть» от «claim отсутствует».",
                verbose_name="Версия аутентификации",
            ),
        ),
    ]
