# Generated by Django 5.2.17 on 2026-09-20 11:44

import django.db.models.functions.text
from django.db import migrations, models

from apps.core.migration_operations import AddIndexSafely


class Migration(migrations.Migration):
    """Индексы студентов, обоснованные планами EXPLAIN (docs/PERFORMANCE.md).

    atomic = False обязателен: PostgreSQL не допускает
    CREATE INDEX CONCURRENTLY внутри транзакции (ТЗ п.54).
    """

    atomic = False

    dependencies = [
        ('students', '0004_student_auth_version'),
        ('universities', '0003_university_is_registration_open'),
    ]

    operations = [
        AddIndexSafely(
            model_name='student',
            index=models.Index(django.db.models.functions.text.Upper('email'), name='student_email_upper_idx'),
        ),
        AddIndexSafely(
            model_name='student',
            index=models.Index(models.F('university'), django.db.models.functions.text.Upper('student_id'), name='student_uni_code_upper_idx'),
        ),
        AddIndexSafely(
            model_name='student',
            index=models.Index(fields=['university', 'is_active'], name='student_uni_active_idx'),
        ),
    ]
