# Generated by Django 5.2.17 on 2026-09-20 11:49

import django.db.models.functions.text
from django.db import migrations, models


def check_no_duplicate_emails(apps, schema_editor):
    """Останавливает миграцию, если в базе есть дубликаты email (ТЗ п.15).

    ТЗ прямо запрещает автоматически чинить такие данные: решение, какой
    из двух аккаунтов настоящий, может принять только человек. Поэтому
    миграция падает с понятной инструкцией, ничего не трогая.
    """
    from collections import defaultdict

    Student = apps.get_model('students', 'Student')
    buckets = defaultdict(list)
    rows = Student.objects.exclude(email__isnull=True).exclude(email='').values(
        'id', 'email', 'student_id', 'university__code'
    )
    for row in rows:
        buckets[row['email'].strip().lower()].append(row)

    duplicates = {email: items for email, items in buckets.items() if len(items) > 1}
    if not duplicates:
        return

    lines = [
        f"Найдено дубликатов email: {len(duplicates)}. "
        "Миграция остановлена, данные не изменены.",
        "",
    ]
    for email, items in sorted(duplicates.items())[:20]:
        lines.append(f"  {email}:")
        for item in items:
            lines.append(
                f"    id={item['id']} student_id={item['student_id']} "
                f"вуз={item['university__code']}"
            )
    if len(duplicates) > 20:
        lines.append(f"  ... и ещё {len(duplicates) - 20}")
    lines += [
        "",
        "Что делать: решите вручную, какой аккаунт оставить, у остальных",
        "очистите email или задайте другой. Затем повторите миграцию.",
        "Полный список: python manage.py audit_db_data",
    ]
    raise RuntimeError("\n".join(lines))


def noop_reverse(apps, schema_editor):
    """Откат проверки не требует действий — она ничего не меняла."""



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_student_email_upper_idx_and_more'),
        ('universities', '0003_university_is_registration_open'),
    ]

    operations = [
        # Проверка идёт ПЕРЕД созданием констрейнта: иначе PostgreSQL
        # отверг бы его сам, но с непонятным сообщением про индекс.
        migrations.RunPython(check_no_duplicate_emails, noop_reverse),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(models.Q(('email', None), _negated=True), models.Q(('email', ''), _negated=True)), name='uniq_student_email_lower'),
        ),
    ]
