# Generated by Django 5.2.17 on 2026-09-20 16:36

from django.db import migrations, models


def invalidate_open_sessions(apps, schema_editor):
    """Гасит открытые сессии подтверждения перед удалением поля с кодом.

    Хэш из открытого кода здесь не восстановить — оно и не нужно: сессия
    живёт 10 минут, и в момент миграции их единицы. Но потерять их молча
    нельзя: студент, ожидающий SMS, должен получить понятный отказ
    и запросить код заново, а не наткнуться на «неверный код».
    """
    StudentAuthSession = apps.get_model('students', 'StudentAuthSession')
    affected = StudentAuthSession.objects.filter(is_verified=False).delete()[0]
    if affected:
        print(f"    Погашено открытых сессий подтверждения: {affected}. "
              f"Ожидающим студентам потребуется запросить код заново.")


def noop_reverse(apps, schema_editor):
    """Откат ничего не восстанавливает: кодов в открытом виде больше нет."""



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_uniq_student_email_lower'),
    ]

    operations = [
        # Сначала гасим сессии, потом удаляем поле с кодом
        migrations.RunPython(invalidate_open_sessions, noop_reverse),
        migrations.RemoveField(
            model_name='studentauthsession',
            name='code',
        ),
        migrations.AddField(
            model_name='studentauthsession',
            name='code_hash',
            field=models.CharField(default='', max_length=255, verbose_name='Хэш кода подтверждения'),
        ),
    ]
