# Generated by Django 6.1.1 on 2026-09-16 08:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название выборов (RU)')),
                ('title_ky', models.CharField(max_length=255, verbose_name='Шайлоонун аталышы (KY)')),
                ('description', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_ky', models.TextField(blank=True, verbose_name='Сүрөттөмөсү (KY)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланированы'), ('active', 'Активны (идет голосование)'), ('finished', 'Завершены'), ('cancelled', 'Отменены')], default='draft', max_length=20, verbose_name='Статус')),
                ('starts_at', models.DateTimeField(verbose_name='Дата и время начала')),
                ('ends_at', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('results_visible_to_admin_before_finish', models.BooleanField(default=False, verbose_name='Результаты видны администратору до завершения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elections', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Выборы',
                'verbose_name_plural': 'Выборы',
                'ordering': ['-starts_at'],
            },
        ),
    ]
