# Generated by Django 5.2.7 on 2026-09-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='elections/covers/', verbose_name='Обложка для карточки'),
        ),
        migrations.AddField(
            model_name='election',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', verbose_name='URL обложки карточки'),
        ),
        migrations.AddField(
            model_name='election',
            name='featured_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке «Последние выборы»'),
        ),
        migrations.AddField(
            model_name='election',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать в блоке «Последние выборы»'),
        ),
    ]
