# Generated by Django 5.2.17 on 2026-09-20 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_election_cover_image_election_cover_image_url_and_more"),
        ("universities", "0003_university_is_registration_open"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="election",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="election_starts_before_ends",
            ),
        ),
    ]
