# Generated by Django 6.1.1 on 2026-09-16 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('elections', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cast_at', models.DateTimeField(auto_now_add=True, verbose_name='Время опускания бюллетеня')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='candidates.candidate', verbose_name='Выбранный кандидат')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.election', verbose_name='Выборы')),
            ],
            options={
                'verbose_name': 'Анонимный бюллетень',
                'verbose_name_plural': 'Анонимные бюллетени',
                'indexes': [models.Index(fields=['election', 'candidate'], name='voting_ball_electio_64afab_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Время голосования')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.election', verbose_name='Выборы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Факт участия в голосовании',
                'verbose_name_plural': 'Факты участия в голосовании',
                'indexes': [models.Index(fields=['election', 'student'], name='voting_vote_electio_fe882d_idx')],
                'unique_together': {('election', 'student')},
            },
        ),
    ]
