# Generated by Django 5.2.17 on 2026-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_election_election_starts_before_ends"),
        ("students", "0003_student_photo"),
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="voterecord",
            name="voting_vote_electio_fe882d_idx",
        ),
        migrations.AlterUniqueTogether(
            name="voterecord",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="voterecord",
            constraint=models.UniqueConstraint(
                fields=("election", "student"), name="uniq_voterecord_election_student"
            ),
        ),
    ]
